name: CI - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Rust & Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: |
          rustup target add x86_64-unknown-linux-gnu
          pip install --upgrade pip setuptools wheel maturin pytest pytest-cov

      - name: Set Up Python Virtual Environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/lib/python3.12/site-packages" >> $GITHUB_PATH

      - name: Build Python Package
        run: maturin develop --target-dir target

      - name: Run Python Tests
        run: pytest tests

      - name: Run Tests with Coverage
        run: pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
